version: '3.7'
services:
    web:
        build: .
        container_name: "php74-1"
        volumes:
            - "./html/:/var/www/html"
        privileged: true
        ports:
            - "8000:80"
        depends_on:
            - mysql
    mysql:
        image: mysql:8
        volumes:
            - ./mysql:/var/lib/mysql
            - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test_db
            - MYSQL_USER=test_user
            - MYSQL_PASSWORD=test_password
        ports:
            - "3306:3306"
        container_name: mysql8-1
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
        - mysql
        environment:
        - PMA_ARBITRARY=1
        - PMA_HOSTS=mysql
        - PMA_USER=test_user
        - PMA_PASSWORD=test_password
        ports:
        - "8080:80"
        volumes:
        - ./phpmyadmin/sessions:/sessions